# Generated by Django 4.2.3 on 2023-07-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
    ]
