# Generated by Django 4.2.3 on 2023-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_rename_dishes_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='id',
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
