# Generated by Django 4.2.3 on 2023-07-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_remove_dish_id_alter_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
